-- Workout library: media columns + labeled seed rows (media URLs left null)
-- Apply after 00001–00004

alter table public.exercises
  add column if not exists slug text,
  add column if not exists image_url text,
  add column if not exists focus_area text;

create unique index if not exists exercises_slug_key
  on public.exercises (slug);

create index if not exists exercises_focus_area_idx
  on public.exercises (focus_area);

comment on column public.exercises.slug is
  'Stable key for media filenames and deep links (e.g. seated-shoulder-press).';

comment on column public.exercises.image_url is
  'Optional photo/thumbnail URL. Leave null until you upload your own asset.';

comment on column public.exercises.video_url is
  'Optional demo video URL. Leave null until you upload your own asset.';

comment on column public.exercises.focus_area is
  'UI grouping: seated_upper, seated_core, seated_cardio, limited_lower, limited_upper, full_mobility, assisted, bands_weights.';

-- Seed catalog (idempotent on slug). video_url and image_url stay null on purpose.
insert into public.exercises as e (
  slug, name, description, instructions, difficulty, equipment, target_muscles,
  mobility_category, focus_area, safety_notes, variations, video_url, image_url
)
values
  ('seated-shoulder-press', 'Seated Shoulder Press',
   'Overhead press from a seated or wheelchair position to build shoulder strength.',
   'Sit tall with core braced. Press weights or bands from shoulder height to overhead without arching the low back. Lower with control.',
   'beginner', array['dumbbells','resistance_bands','wheelchair_accessible'], array['shoulders','triceps'],
   'seated', 'seated_upper',
   'Keep elbows slightly forward of the torso. Stop if you feel sharp shoulder pain.',
   '["Single-arm seated press","Band overhead press"]'::jsonb, null, null),
  ('seated-lat-pulldown-band', 'Seated Lat Pulldown (Band)',
   'Pull a resistance band downward to train the back from a seated position.',
   'Anchor the band overhead or high. Sit tall, pull elbows down toward the ribs, then return slowly.',
   'beginner', array['resistance_bands','wheelchair_accessible'], array['lats','biceps','upper_back'],
   'seated', 'seated_upper',
   'Avoid shrugging. Keep ribs stacked over the pelvis.',
   '["Single-arm pulldown","Wide-grip pulldown"]'::jsonb, null, null),
  ('seated-chest-press-band', 'Seated Chest Press (Band)',
   'Press forward against band resistance to strengthen the chest and arms while seated.',
   'Anchor the band behind you at mid-chest height. Press hands forward until elbows nearly straighten, then return.',
   'beginner', array['resistance_bands','wheelchair_accessible'], array['chest','triceps','shoulders'],
   'seated', 'seated_upper',
   'Do not lock elbows aggressively. Keep wrists neutral.',
   '["Single-arm chest press"]'::jsonb, null, null),
  ('seated-row-band', 'Seated Band Row',
   'Horizontal pull for upper-back strength and posture from a chair or wheelchair.',
   'Anchor the band in front at mid-torso height. Pull handles to the ribs, squeeze shoulder blades, then extend.',
   'beginner', array['resistance_bands','wheelchair_accessible'], array['upper_back','biceps','rear_shoulders'],
   'seated', 'seated_upper',
   'Avoid rounding the upper back. Lead with the elbows.',
   '["Neutral-grip row","Pause row"]'::jsonb, null, null),
  ('seated-bicep-curl', 'Seated Bicep Curl',
   'Isolated elbow flexion for arm strength while seated.',
   'Hold dumbbells or bands with arms at your sides. Curl toward the shoulders without swinging, then lower slowly.',
   'beginner', array['dumbbells','resistance_bands','wheelchair_accessible'], array['biceps'],
   'seated', 'seated_upper',
   'Keep elbows pinned near the torso; avoid leaning back.',
   '["Hammer curl","Alternating curl"]'::jsonb, null, null),
  ('seated-overhead-tricep-extension', 'Seated Overhead Tricep Extension',
   'Tricep strengthener performed overhead from a stable seat.',
   'Hold one dumbbell or band handle overhead. Bend elbows to lower behind the head, then extend.',
   'intermediate', array['dumbbells','resistance_bands','wheelchair_accessible'], array['triceps'],
   'seated', 'seated_upper',
   'Keep upper arms close to the ears; protect the neck.',
   '["Single-arm extension"]'::jsonb, null, null),
  ('seated-march', 'Seated March',
   'Low-impact cardio and hip mobility by marching in place while seated.',
   'Sit tall. Lift one knee at a time as if marching. Swing opposite arm gently if able. Keep a steady rhythm.',
   'beginner', array['none','wheelchair_accessible'], array['hip_flexors','core'],
   'seated', 'seated_cardio',
   'Stay within a pain-free range. Hold chair sides if balance is limited.',
   '["High-knee seated march","March with arm drive"]'::jsonb, null, null),
  ('seated-shadow-boxing', 'Seated Shadow Boxing',
   'Upper-body cardio using punches from a seated or wheelchair base.',
   'Guard hands near the face. Alternate jabs and crosses with light rotation through the torso. Breathe steadily.',
   'beginner', array['none','wheelchair_accessible'], array['shoulders','core','arms'],
   'seated', 'seated_cardio',
   'Keep punches controlled. Avoid hyperextending elbows.',
   '["Jab-cross only","Add hooks"]'::jsonb, null, null),
  ('seated-torso-rotation', 'Seated Torso Rotation',
   'Gentle rotational mobility for the mid-back and core.',
   'Sit tall, hands at chest or on a light ball. Rotate slowly left and right while keeping hips facing forward.',
   'beginner', array['none','wheelchair_accessible'], array['obliques','mid_back'],
   'seated', 'seated_core',
   'Move within comfort. Stop if you feel spine pain.',
   '["Hold at end range","Band-resisted rotation"]'::jsonb, null, null),
  ('seated-dead-bug', 'Seated Dead Bug Reach',
   'Core control drill adapted to a chair—opposite arm and knee reach.',
   'Sit tall. Extend one arm forward while the opposite knee lifts slightly. Alternate sides with control.',
   'intermediate', array['none','wheelchair_accessible'], array['core','hip_flexors'],
   'seated', 'seated_core',
   'Do not arch the low back. Exhale on the reach.',
   '["Arms only","Knees only"]'::jsonb, null, null),
  ('chair-supported-sit-to-stand', 'Chair-Supported Sit-to-Stand',
   'Functional strength for standing up using chair support as needed.',
   'Scoot forward, feet flat. Lean slightly forward, push through legs to stand, using armrests if needed. Sit down with control.',
   'beginner', array['none'], array['quads','glutes','core'],
   'limited_lower', 'limited_lower',
   'Use a stable chair. Have a spotter if balance is uncertain.',
   '["Higher seat","Pause at stand"]'::jsonb, null, null),
  ('supported-calf-raise', 'Supported Calf Raise',
   'Ankle and calf strength with hand support for balance.',
   'Hold a counter or chair back. Rise onto the balls of the feet, pause, then lower slowly.',
   'beginner', array['none'], array['calves'],
   'limited_lower', 'limited_lower',
   'Keep knees soft. Stop if ankles feel unstable.',
   '["Single-leg supported raise"]'::jsonb, null, null),
  ('standing-hip-abduction-support', 'Standing Hip Abduction (Supported)',
   'Side-leg lifts with support to strengthen outer hips.',
   'Hold a stable surface. Lift one leg out to the side without leaning the torso. Return slowly.',
   'beginner', array['none'], array['glute_medius','hips'],
   'limited_lower', 'limited_lower',
   'Keep toes forward. Do not hike the hip.',
   '["Mini-band around ankles"]'::jsonb, null, null),
  ('wall-push-up', 'Wall Push-Up',
   'Upper-body push with reduced load—ideal when floor push-ups are limited.',
   'Hands on wall at chest height. Lower chest toward the wall by bending elbows, then press away.',
   'beginner', array['none'], array['chest','triceps','shoulders'],
   'limited_upper', 'limited_upper',
   'Keep a straight line from head to heels or knees as able.',
   '["Counter push-up","Kneeling wall progression"]'::jsonb, null, null),
  ('scapular-retraction', 'Scapular Retraction (Posture Drill)',
   'Shoulder-blade squeezes to support posture for limited upper mobility.',
   'Sit or stand tall. Squeeze shoulder blades together gently, hold briefly, then release.',
   'beginner', array['none','wheelchair_accessible'], array['upper_back','rear_shoulders'],
   'limited_upper', 'limited_upper',
   'Keep shoulders down—avoid shrugging toward ears.',
   '["Band pull-apart"]'::jsonb, null, null),
  ('assisted-sit-to-stand-partner', 'Assisted Sit-to-Stand',
   'Sit-to-stand with caregiver or rail assistance for safety.',
   'With a trained spotter or secure rail, practice rising and sitting. Helper supports as agreed—never pulls on arms aggressively.',
   'beginner', array['none'], array['quads','glutes','core'],
   'assisted', 'assisted',
   'Use a gait belt if trained. Clear space for falls. Stop if dizzy.',
   '["Partial stand","Higher chair"]'::jsonb, null, null),
  ('assisted-arm-raise', 'Assisted Arm Raise',
   'Guided shoulder flexion with partner or self-assist using the other arm.',
   'Support the working arm at the wrist/elbow. Raise within a comfortable range, then lower.',
   'beginner', array['none'], array['shoulders'],
   'assisted', 'assisted',
   'Never force through pain. Move slowly.',
   '["Table slide assist"]'::jsonb, null, null),
  ('bodyweight-squat', 'Bodyweight Squat',
   'Foundational lower-body strength for members with full mobility.',
   'Feet about shoulder-width. Sit hips back and down, keep heels down, then stand. Arms can reach forward for balance.',
   'beginner', array['none'], array['quads','glutes','core'],
   'full', 'full_mobility',
   'Knees track over mid-foot. Depth only as comfortable.',
   '["Box squat","Pause squat"]'::jsonb, null, null),
  ('glute-bridge', 'Glute Bridge',
   'Hip extension on the floor or firm mat for posterior chain strength.',
   'Lie on your back, knees bent, feet flat. Drive through heels to lift hips, squeeze glutes, then lower.',
   'beginner', array['none'], array['glutes','hamstrings','core'],
   'full', 'full_mobility',
   'Do not over-arch the low back. Keep ribs down.',
   '["Single-leg bridge","Feet elevated"]'::jsonb, null, null),
  ('bird-dog', 'Bird Dog',
   'Opposite arm and leg reach for core and spinal stability.',
   'On hands and knees, extend one arm and the opposite leg. Hold briefly, return, switch sides.',
   'intermediate', array['none'], array['core','glutes','back'],
   'full', 'full_mobility',
   'Keep hips level. Avoid rotating the pelvis.',
   '["Hold 3 seconds","Knee-hover bird dog"]'::jsonb, null, null),
  ('band-pull-apart', 'Band Pull-Apart',
   'Rear-shoulder and upper-back activation with a light band.',
   'Hold a band at shoulder height. Pull apart until arms are wide, squeeze, then return with control.',
   'beginner', array['resistance_bands'], array['rear_shoulders','upper_back'],
   'full', 'bands_weights',
   'Use a light band. Keep elbows soft.',
   '["Diagonal pull-apart"]'::jsonb, null, null),
  ('dumbbell-goblet-squat', 'Dumbbell Goblet Squat',
   'Squat pattern loaded with a dumbbell held at the chest.',
   'Hold one dumbbell vertically at the chest. Squat down with upright torso, then stand.',
   'intermediate', array['dumbbells'], array['quads','glutes','core'],
   'full', 'bands_weights',
   'Choose a manageable weight. Heels stay down.',
   '["Heel-elevated goblet squat"]'::jsonb, null, null),
  ('dumbbell-romanian-deadlift', 'Dumbbell Romanian Deadlift',
   'Hinge pattern for hamstrings and glutes with dumbbells.',
   'Soft knees. Hinge at hips, push hips back, lower dumbbells along the thighs, then stand tall by driving hips forward.',
   'intermediate', array['dumbbells'], array['hamstrings','glutes','back'],
   'full', 'bands_weights',
   'Keep a flat back. Stop before the low back rounds.',
   '["Single-leg RDL (bodyweight first)"]'::jsonb, null, null),
  ('cable-face-pull-adaptive', 'Adaptive Face Pull',
   'Rear-delt and upper-back pull using a cable or band; seated option encouraged.',
   'Pull the handle or band toward the face with elbows high. Squeeze rear shoulders, then return.',
   'intermediate', array['cable_machine','resistance_bands','adaptive_machines'], array['rear_shoulders','upper_back'],
   'seated', 'bands_weights',
   'Use moderate resistance. Avoid yanking the neck forward.',
   '["Seated face pull","Standing face pull"]'::jsonb, null, null)
on conflict (slug)
do update set
  name = excluded.name,
  description = excluded.description,
  instructions = excluded.instructions,
  difficulty = excluded.difficulty,
  equipment = excluded.equipment,
  target_muscles = excluded.target_muscles,
  mobility_category = excluded.mobility_category,
  focus_area = excluded.focus_area,
  safety_notes = excluded.safety_notes,
  variations = excluded.variations,
  updated_at = now();
